version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: pretty-quick
    versions:
    - 2.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: react-dom
    versions:
    - 16.13.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@fortawesome/react-fontawesome"
    versions:
    - 0.1.11
