version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/javascript"
    update_schedule: "daily"
    automerged_updates: 
      - match:
          dependency_type: "all"
          update_type: "all"
